#version: "3.9"

x-health: &health_defaults
  interval: 10s
  timeout: 5s
  retries: 6
  start_period: 20s

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      <<: *health_defaults

  backend:
    image: ghcr.io/project-hearo/hearo-be:latest
    container_name: fastapi_backend
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "(curl -fsS http://localhost:8000/healthz || curl -fsS http://localhost:8000/api/healthz) >/dev/null || exit 1" ]
      <<: *health_defaults


volumes:
  db_data:
